import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import Navbar from './navbar';
import Sidenav from './sidenav';
import QueryProvider from '@/utils/query-provider';

const dmSans = DM_Sans({
  variable: '--font-dm-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} flex justify-center`}>
        <section className="flex w-full max-w-[1728px] justify-center">
          <QueryProvider>
            <div className="flex w-full max-w-[1488px] flex-col gap-[91px] pb-[30px] pt-[25px] max-2xl:px-[120px]">
              <Navbar />
              <div className="flex items-start gap-[82px]">
                <Sidenav />
                {children}
              </div>
            </div>
          </QueryProvider>
        </section>
      </body>
    </html>
  );
}
